export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const AGREGAR_TEMPORADA = 'AGREGAR_TEMPORADA';
export const AGREGAR_TEMPORADA_EXITO = 'AGREGAR_TEMPORADA_EXITO';
export const AGREGAR_TEMPORADA_ERROR = 'AGREGAR_TEMPORADA_ERROR';

export const COMENZAR_DESCARGA_TEMPORADAS = 'COMENZAR_DESCARGA_TEMPORADAS';
export const DESCARGA_TEMPORADAS_EXITO = 'DESCARGA_TEMPORADAS_EXITO';
export const DESCARGA_TEMPORADAS_ERROR = 'DESCARGA_TEMPORADAS_ERROR';

export const OBTENER_TEMPORADA_ELIMINAR = 'OBTENER_TEMPORADA_ELIMINAR';
export const TEMPORADA_ELIMINADA_EXITO = 'TEMPORADA_ELIMINADA_EXITO';
export const TEMPORADA_ELIMINADA_ERROR = 'TEMPORADA_ELIMINADA_ERROR';

export const OBTENER_TEMPORADA_EDITAR = 'OBTENER_TEMPORADA_EDITAR';
export const COMENZAR_EDICION_TEMPORADA = 'COMENZAR_EDICION_TEMPORADA';
export const TEMPORADA_EDITADA_EXITO = 'TEMPORADA_EDITADA_EXITO';
export const TEMPORADA_EDITADA_ERROR = 'TEMPORADA_EDITADA_ERROR';




